### ISSUE TITLE
package ‘fastr’ in options("defaultPackages") was not found

### ISSUE THREAD

**Issue by stanekam** [graalvm/fastr#5]
Hello, 

I tried building fastR based on the linked bitbucket wiki page.  The build seems to run and complete just fine but when I start fastR I get a number of complaints based on not being able to find default packages:

```
Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return  :
  there is no package called ‘fastr’
2:
  package ‘fastr’ in options("defaultPackages") was not found
3:
  package ‘datasets’ in options("defaultPackages") was not found
4:
  package ‘utils’ in options("defaultPackages") was not found
5:
  package ‘grDevices’ in options("defaultPackages") was not found
6:
  package ‘graphics’ in options("defaultPackages") was not found
7:
  package ‘stats’ in options("defaultPackages") was not found
8:
  package ‘methods’ in options("defaultPackages") was not found
```

I checked my `.libPaths()` and the stated packages appear to be in my `$FASTR_HOME/fastr/library` folder but are failing to be loaded.

One option that I suspect may be the cause is that I built fastR from the source code stored in bitbucket. (i.e. `mx sclone https://username@bitbucket.org/allr/fastr`)

I also noticed that some of the stated effects in the wiki were not the case:

> After this, you should find three directories called fastr, jvmci and graal in the project root.

Can you confirm these are still the instructions that I should be following for the build process?  If not, can someone point me to an updated build process?

Thanks!

**Comment by lukasstadler** [comment]
Hi,

we're currently updating our documentation to reflect the fact that we've moved everything from bitbucket to github (the most up-to-date version is now on github).
We've encountered this specific problem (warnings about missing default packages) very recently, changeset https://github.com/graalvm/fastr/commit/dddbf945296f99287048c3946193edaf9c9d344c fixed it for us. Could you please check if your build includes this changeset?

If you only want to use FastR, and are not interested in building it yourself, you can also download pre-built binaries from OTN (http://www.oracle.com/technetwork/oracle-labs/program-languages/overview/index-2301583.html). These are usually updated once a month.

Best, Lukas
