### ISSUE TITLE
install of package Rcpp fails

### ISSUE THREAD

**Issue by akoltsv** [graalvm/fastr#6]
I am not able to install Rcpp package in FastR. Rcpp package installs without issues on R 3.1 (included in distro) and R 3.3 (from cran3 builds).
Is there any solution or work around? 
Thank you.

`$ mx r`
`FastR version 3.2.4`
`Copyright (c) 2013-16, Oracle and/or its affiliates`
`Copyright (c) 1995-2016, The R Core Team`
`Copyright (c) 2016 The R Foundation for Statistical Computing`
`Copyright (c) 2012-4 Purdue University`
`Copyright (c) 1997-2002, Makoto Matsumoto and Takuji Nishimura`
`All rights reserved.`

`FastR is free software and comes with ABSOLUTELY NO WARRANTY.`
`You are welcome to redistribute it under certain conditions.`
`Type 'license()' or 'licence()' for distribution details.`

`R is a collaborative project with many contributors.`
`Type 'contributors()' for more information.`

`Type 'q()' to quit R.`
`> install.packages("Rcpp", repo="http://cran.cnr.berkeley.edu")`
`tools:::.install_packages()`
`* installing *source* package ‘Rcpp’ ...`
`** package ‘Rcpp’ successfully unpacked and MD5 sums checked`
`** libs`
`g++ -I/home/build/projects/dev/r-lang/fastr/include -DNDEBUG -I../inst/include/ -DLIBICONV_PLUG    -fpic  -DLIBICONV_PLUG  -DFASTR -c Date.cpp -o Date.o`
`g++ -I/home/build/projects/dev/r-lang/fastr/include -DNDEBUG -I../inst/include/ -DLIBICONV_PLUG    -fpic  -DLIBICONV_PLUG  -DFASTR -c Module.cpp -o Module.o`
`g++ -I/home/build/projects/dev/r-lang/fastr/include -DNDEBUG -I../inst/include/ -DLIBICONV_PLUG    -fpic  -DLIBICONV_PLUG  -DFASTR -c Rcpp_init.cpp -o Rcpp_init.o`
`g++ -I/home/build/projects/dev/r-lang/fastr/include -DNDEBUG -I../inst/include/ -DLIBICONV_PLUG    -fpic  -DLIBICONV_PLUG  -DFASTR -c api.cpp -o api.o`
`g++ -I/home/build/projects/dev/r-lang/fastr/include -DNDEBUG -I../inst/include/ -DLIBICONV_PLUG    -fpic  -DLIBICONV_PLUG  -DFASTR -c attributes.cpp -o attributes.o`
`g++ -I/home/build/projects/dev/r-lang/fastr/include -DNDEBUG -I../inst/include/ -DLIBICONV_PLUG    -fpic  -DLIBICONV_PLUG  -DFASTR -c barrier.cpp -o barrier.o`
`g++ -shared -L/usr/local/lib -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o`
`installing to /home/build/projects/dev/r-lang/fastr/library/Rcpp/libs`
`** R`
`** inst`
`** preparing package for lazy loading`
**Error in .RcppClass$methods : object of type 'closure' is not subsettable
Error: unable to load R code in package ‘Rcpp’**
`* removing ‘/home/build/projects/dev/r-lang/fastr/library/Rcpp’`

`The downloaded source packages are in`
`‘/tmp/Rtmp3WkG5x/downloaded_packages’`
`Updating HTML index of packages in '.Library'`
`Making 'packages.html' ... done`
`Warning message:`
`In install.packages("Rcpp", repo = "http://cran.cnr.berkeley.edu") : installation of package ‘Rcpp’ had non-zero exit status`

$ uname -a
Linux amd 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.5-1~bpo8+1 (2016-09-30) x86_64 GNU/Linux

$ java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by lukasstadler** [comment]
unfortunately FastR is not quite ready to run Rcpp, because this package requires a very large degree of completeness in the native interface.
sorry that we've wasted your time on this - we hope to have a website soon that will show which packages do and which do not work on FastR.

that being said, if you were thinking about implementing something in C++ because of performance concerns, you should give it a try in pure R: FastR is executing R code much, much faster than GNUR.

**Comment by akoltsv** [comment]
For my use case FastR seems to be the best option. Essentially I need to run R code that uses a few functions from plyr which depends on Rcpp. I think with some modifications to plyr I might be able to make it work without Rcpp.
Thanks for quick response and clarification.
