### ISSUE TITLE
read.csv() breaks when using | (pipe) delimited CSV

### ISSUE THREAD

**Issue by rothn** [graalvm/fastr#7]
**Problem:**
read.csv() breaks when using | (pipe) delimited CSV

**Cause:**
This probably uses a RegEx pattern to match the delimiter. Unfortunately, "|" is a metacharacter in regex. The Java RegEx engine interprets the pattern `/|/` as an expression that can match zero characters, and therefore matches infinitely. Running `"asdf".split("|")` in Java returns an array `a, s, d, f`

**1) Consider a script that produces a CSV file delimited by pipes (|)**
 _For some reason, let's say it's the only delimiter that makes sense_
**2) Attempt to run the command:**
`db_jira_rec <- read.csv("/Users/xxxxx/auto_sprint_mgr_broken_new/training/big_jira2.csv", sep="|", ...)`
**3) Print db_jira_rec:**
```
> db_jira_rec
  V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15 V16 V17 V18 V19 V20 V21
1  t  h  i  s  _  i  s  _  h   o   w   _   t   h   e   _   o   u   t   p   u
  V22 V23 V24 V25 V26 V27 V28 V29 V30 V31 V32 V33 V34 V35 V36 V37 V38 V39 V40
1   t   _   l   o   o   k   s   _   b   u   t   _   O   r   a   c   l   e   _
  V41 V42 V43 V44 V45 V46 V47 V48 V49 V50 V51 V52 V53 V54 V55 V56 V57 V58 V59
1   w   o   u   l   d   _   g   e   t   _   m   a   d   _   i   f   _   I   _
  V60 V61 V62 V63 V64 V65 V66 V67 V68 V69 V70 V71 V72 V73 V74 V75 V76 V77 V78
1   p   o   s   t   e   d   _   d   a   t   a   _   f   r   o   m   _   t   h
  V79 V80 V81 V82 V83 V84 V85 V86 V87 V88 V89 V90 V91 V92 V93 V94 V95 V96 V97
1   e   i   r   _   J   I   R   A   _   d   a   t   a   b   a   s   e   _   _
...
...
...
```

**Comment by lukasstadler** [comment]
thanks for the report! I'll fix it.

**Comment by lukasstadler** [comment]
should be fixed with https://github.com/graalvm/fastr/commit/093dbbede47761c1be264f35b9d40864dd56b038
