### ISSUE TITLE
Building problem in Ubuntu 16.04

### ISSUE THREAD

**Issue by colmillo-blanco** [graalvm/fastr#9]
Hi everyone, I am struggling a bit trying to understand what I am doing wrong, following the building instructions on the main page. 
I have all necessary packages and the JAVA_HOME pointing out to jvmci folder. Here are my results:

rm -rf R-3.3.2
rm -f Makeconf.done
make[3]: Leaving directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
make -f Makefile.libs clean
make[3]: Entering directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
rm -f /home/user/fastR/fastr/lib/libRblas /home/user/fastR/fastr/lib/libRlapack 
rm -f     
rm -f rcopylib.done
make[3]: Leaving directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
make -f Makefile.platform clean
make[3]: Entering directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
rm -f /home/user/fastR/fastr/com.oracle.truffle.r.native/platform.mk
make[3]: Leaving directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
make[2]: Leaving directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
make[1]: Leaving directory '/home/user/fastR/fastr/com.oracle.truffle.r.native'
make -C gnur
make[1]: Entering directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
make -f Makefile.gnur
make[2]: Entering directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
tar xf /home/user/fastR/fastr/com.oracle.truffle.r.native/../libdownloads/R-3.3.2.tar.gz
ed /home/user/fastR/fastr/com.oracle.truffle.r.native/gnur/R-3.3.2/configure < edconfigure # to fix the zlib version check (fixed in GNUR in the meantime)
1473634
1473529
(cd /home/user/fastR/fastr/com.oracle.truffle.r.native/gnur/R-3.3.2; ./configure --with-x=no --with-aqua=no "--without-recommended-packages" --enable-memory-profiling  FFLAGS=-O2  > gnur_configure.log 2>&1)
Makefile.gnur:160: recipe for target '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur/R-3.3.2/Makefile' failed
make[2]: *** [/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur/R-3.3.2/Makefile] Error 1
make[2]: Leaving directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
Makefile:31: recipe for target 'makegnur' failed
make[1]: *** [makegnur] Error 2
make[1]: Leaving directory '/home/user/fastR/fastr/com.oracle.truffle.r.native/gnur'
Makefile:46: recipe for target 'all' failed
make: *** [all] Error 2

Building com.oracle.truffle.r.native with GNU Make failed
1 build tasks failed

Thanks everyone in advance.

**Comment by lukasstadler** [comment]
the R build process is somewhat tricky, because it involves a full build of the GNU R engine for testing.
please take a look at the /home/user/fastR/fastr/com.oracle.truffle.r.native/gnur/R-3.3.2/gnur_configure.log file - this will give you hints as to what is the actual problem.

**Comment by colmillo-blanco** [comment]
Thanks I'll do that

**Comment by colmillo-blanco** [comment]
Thanks lukasstadler , I finally was able to solve the problem by compiling libcurl from source. For anyone on ubuntu this is what I had to do:
sudo apt-get install build-essential nghttp2 libnghttp2-dev 
wget https://curl.haxx.se/download/curl-7.54.0.tar.bz2
tar -xvjf curl-7.54.0.tar.bz2
cd curl-7.54.0
./configure --with-nghttp2 --prefix=/usr/local
make
sudo make install
sudo ldconfig


Credit should go to the following link: 
https://askubuntu.com/questions/884899/how-do-i-install-curl-with-http2-support
